SET_EXPR( ${MODULE_NAME_UPPER}_EXCLUDE_EXPRESSION NOT(TARGET_OS_POSIX_QNX OR TARGET_OS_WIN32 OR TARGET_OS_POSIX_LINUX OR TARGET_OS_POSIX_OLDLINUX OR TARGET_OS_CYGWIN) )

# Direct dependencies of this module
SET(${MODULE_NAME_UPPER}_DEPENDENCIES "")

SET(${MODULE_NAME_UPPER}_INCLUDES ${${MODULE_NAME_UPPER}_INCLUDES} ${MODULE_PATH}/src)

SET(${MODULE_NAME_UPPER}_DEFINITIONS ${${MODULE_NAME_UPPER}_DEFINITIONS} "")
SET(${MODULE_NAME_UPPER}_DEFINITIONS "HAVE_CONFIG_H")

# Linker settings
SET (${MODULE_NAME_UPPER}_LINK_LIBRARIES ${MODULE_NAME})
